### ISSUE TITLE
Error Task exception was never retrieved

### ISSUE THREAD

**Issue by Arcade75** [Hassassistant/openai_response#10]
Hello

Thanks for your integration. I have this error and I am pretty sure I followed all the steps:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
KeyError: 0

Thanks

**Comment by Arcade75** [comment]
I am sorry, I was referring to OpenMindsAI instead of this integration!!

You can close this issue

**Comment by Hassassistant** [comment]
no problem thanks for updating.
