### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by KongDeyu1532** [Hassassistant/openai_response#11]
After entering text in the text box, there is no output below.

**Comment by Hassassistant** [comment]
Could you provide further error logs to support this issue?

**Comment by KongDeyu1532** [comment]
After following the steps above to configure, I was able to get the input text box to appear. However, when I entered some questions into the text box and pressed the enter key, the ChatGPT Response below did not respond. I'm not sure if the message was sent but no results were returned, or if the message was not sent at all.

**Comment by VNDCK** [comment]
I'm trying to get this to work, but I don't get a response either. Not sure where I can get some logs for this?

**Comment by Astogems** [comment]
It is most probably because you have no free trial credits left.

You have to sign up for the pro plan, its a pay as you go service.

After you have signed up for pro plan, create a new API Key and it will work.

**Comment by Whizzykid** [comment]
I'm having the same issue, but I can see that I have credits in my account (the free $18)

Any advice?

**Comment by Crimby88** [comment]
Same here. I have $5 in my account for usage, I see the input block, but no response.

From logbook:

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/openai_response/sensor.py:32
Integration: openai_response (documentation)
First occurred: 11:23:26 (2 occurrences)
Last logged: 11:27:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openai_response/sensor.py", line 66, in async_generate_openai_response
    response = await self._hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openai_response/sensor.py", line 32, in generate_openai_response_sync
    return openai.Completion.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations
